### ISSUE TITLE
check-previews-compile.js requires glob < 9

### ISSUE THREAD

**Issue by sparksp** [jfmengels/node-elm-review#105]
New major version of [glob v9.0.1](https://www.npmjs.com/package/glob/v/9.0.1) has changed the interface which will break `elm-review-package-tests/helpers/find-configurations.js`. Hopefully a fairly easy fix.

```
./elm-review-always/elm-review-package-tests/helpers/find-configurations.js:15
    .sync(`${root}/preview*/**/elm.json`, {
     ^

TypeError: glob.sync is not a function
    at findPreviewConfigurations (./elm-review-always/elm-review-package-tests/helpers/find-configurations.js:15:6)
    at Object.<anonymous> (./elm-review-package-tests/check-previews-compile.js:12:1)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47
```

**Comment by jfmengels** [comment]
Fixed in 58e1ebfb614bb233a1f8158f36c1a9766a172dbd
