### ISSUE TITLE
Error adding maintenance scripts

### ISSUE THREAD

**Issue by sparksp** [jfmengels/node-elm-review#17]
`elm-review new-package` using version 2.3.0 installed with yarn.

```
✖ Adding maintenance scripts
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
Error: ENOENT: no such file or directory, stat '/Users/phills/.config/yarn/global/node_modules/elm-review/new-package/maintenance/'
    at Object.statSync (fs.js:1042:3)
    at Object.statSync (/Users/phills/.config/yarn/global/node_modules/graceful-fs/polyfills.js:307:34)
    at statSync (/Users/phills/.config/yarn/global/node_modules/fs-extra/lib/util/stat.js:10:52)
    at getStatsSync (/Users/phills/.config/yarn/global/node_modules/fs-extra/lib/util/stat.js:24:19)
    at Object.checkPathsSync (/Users/phills/.config/yarn/global/node_modules/fs-extra/lib/util/stat.js:49:33)
    at Object.copySync (/Users/phills/.config/yarn/global/node_modules/fs-extra/lib/copy-sync/copy-sync.js:24:38)
    at createProject (/Users/phills/.config/yarn/global/node_modules/elm-review/lib/new-package.js:251:6)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async newPackage (/Users/phills/.config/yarn/global/node_modules/elm-review/lib/new-package.js:70:5)
```

**Comment by jfmengels** [comment]
Fixed in 2.3.1. Thanks for reporting :)
