### ISSUE TITLE
Handle invalid argument types

### ISSUE THREAD

**Issue by lydell** [jfmengels/node-elm-review#26]
```
❯ ~/forks/node-elm-review/bin/elm-review --compiler
-- UNEXPECTED ERROR ------------------------------------------------------------

I ran into an unexpected error. Please open an issue at the following link:
  https://github.com/jfmengels/node-elm-review/issues/new

Please include this error message and as much detail as you can provide. If you
can, please provide a setup that makes it easy to reproduce the error. That will
make it much easier to fix the issue.

Below is the error that was encountered.
--------------------------------------------------------------------------------
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean (true)
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:980:7)
    at getElmBinary (/Users/lydell/forks/node-elm-review/lib/elm-binary.js:26:26)
    at buildLocalProject (/Users/lydell/forks/node-elm-review/lib/build.js:126:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runElmReview (/Users/lydell/forks/node-elm-review/lib/main.js:48:42)
```

I think this error should be handled.

**Comment by jfmengels** [comment]
Haha, are you test-stressing my minimist implementation? :smile: 
You're right, this is definitely problematic and should be handled better :+1:
