### ISSUE TITLE
The "mode" argument must be integer

### ISSUE THREAD

**Issue by sparksp** [jfmengels/node-elm-review#8]
I get the following error when trying to init within a package...

```
$ elm-review init --debug
✔ Would you like me to create elm.json and src/ReviewConfig.elm inside /redacted/sparksp/elm-project/review? … yes
TypeError [ERR_INVALID_ARG_TYPE]: The "mode" argument must be integer. Received an instance of Object
    at Object.copyFileSync (fs.js:1905:10)
    at createReviewConfig (/Users/phills/sparksp/elm-review-ports/node_modules/elm-review/lib/init.js:82:6)
    at initializeProject (/Users/phills/sparksp/elm-review-ports/node_modules/elm-review/lib/init.js:30:3)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

The command exits with code `1`.  It has generated `review/elm.json` and created `review/src` but there's no `ReviewConfig.elm`.

**Comment by sparksp** [comment]
Here's the problem in [/lib/init.js:83](https://github.com/jfmengels/node-elm-review/blame/92cc02997b994750f01ef6a675160c9e3055fe52/lib/init.js#L83) - The 3rd argument (mode) for [`copyFileSync`](https://nodejs.org/docs/latest/api/fs.html#fs_fs_copyfilesync_src_dest_mode) should be an integer. Furthermore, dest is overwritten if it already exists by default so no option should be needed.
